# Generated by Django 3.2.23 on 2023-12-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='music_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='')),
                ('singer', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=80)),
                ('place', models.CharField(max_length=80)),
                ('post', models.CharField(max_length=80)),
                ('pin', models.IntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drs_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='playlist_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=80)),
                ('MUSIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drs_app.music_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drs_app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='drowsiness_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drs_app.user_table')),
            ],
        ),
    ]
