# Generated by Django 3.2.23 on 2024-01-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drowsiness_table',
            name='status',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
