# Generated by Django 3.2.23 on 2024-01-10 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drs_app', '0002_drowsiness_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist_table',
            name='emotion',
        ),
        migrations.AddField(
            model_name='music_table',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drs_app.login_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music_table',
            name='emotion',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
