# Generated by Django 3.2.23 on 2024-01-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drs_app', '0003_auto_20240110_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_table',
            name='emotion',
        ),
    ]
