# Generated by Django 5.0.1 on 2024-01-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs_app', '0004_remove_music_table_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drowsiness_table',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='music_table',
            name='year',
            field=models.TextField(),
        ),
    ]
